version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.11.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-1-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-1-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: "."
          paths:
            - node_modules

  test:
    docker:
      - image: cimg/node:15.11.0

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: "."

      - run: npm run test
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: ./reports/junit
      - run:
          name: Notify Test Results
          command: node ./scripts/parseJunit.js
          when: always

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
